name: Notify Slack on release branch creation
on: create

jobs:
  notify_merged_pull_request:
    name: Notify Slack on creation of release branch
    runs-on: ubuntu-latest
    if: ${{ (github.event.ref_type == 'branch') && startsWith(github.event.ref, 'release-') }}
    steps:
      - uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
            args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*axon-ui:* Release branch created ${GITHUB_REF#refs/heads/}!\"}}]}'
        if: success()
